### DataBase ###
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/qg_official_website
    username: root
    password: 970228
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,wall,log4j
    maxActive: 20
    initialSize: 5
    maxWait: 60000
    minIdle: 5
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    maxPoolPreparedStatementPerConnectionSize: 20
  jpa:
    show-sql: true
    database: mysql
  mvc:
    static-path-pattern: /**
  devtools:
    restart:
      enabled: true

# Mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qg.officialwebsite.domain
  configuration:
    mapUnderscoreToCamelCase: true # 开启驼峰命名转换法
    lazy-loading-enabled: true
    use-generated-keys: true
    aggressive-lazy-loading: false # 延迟加载

# 分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql